[package]
name = "version-bump"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
regex = "1.9"
xmltree = "0.11.0"
serde_yaml = "0.9.34"
plist = "1.5"

[profile.release]
strip=true
